export const data = [
  {
    index: 0,
    image: "/images/ai-img.png",
    projectName: "AI Image Generator",
    projectLink: "https://zareen-ai-image-gen.vercel.app",
    projectDescription:
      "Imagify is your go-to platform for turning text into stunning AI-generated images in seconds. Just type in your idea, and let the magic happen! You can easily generate, download, and share your creations. Plus, explore a gallery of the latest images generated by others for inspiration.",
    projectTech: ["Nextjs", "TypeScript", "Express", "Prisma", "MongoDB"],
    projectExternalLinks: {
      github: "https://github.com/zareenf01/ai-image-gen",
      externalLink: "",
    },
  },
  {
    index: 1,
    image: "/images/anime.png",
    projectName: "AniList",
    projectLink: "https://zareen-anime.netlify.app/",
    projectDescription:
      "AniList is a website dedicated to anime enthusiasts, it is a React-based anime website that leverages the Jikan API to provide users with a platform to explore, discover, and keep track of their favorite anime series and movies.",
    projectTech: ["React", "Tailwind", "ContextAPI", "JikanApi"],
    projectExternalLinks: {
      github: "https://github.com/zareenf01/AniList",
      externalLink: "",
    },
  },
  {
    index: 2,
    image: "/images/skincare.png",
    projectName: "E-commerce skincare",
    projectLink: "https://zareen-skincare.netlify.app/",
    projectDescription:
      "Skincare is a full stack React-based web application dedicated to skincare products, routines, and tips. With features such as a skin type quiz for personalized recommendations, an intuitive Add to Cartfunctionality, and Product details. users can easily discover tailored skincare solutions and streamline their shopping experience.",
    projectTech: ["React", "Express", "Prisma", "PostgreSQL"],
    projectExternalLinks: {
      github: "https://github.com/zareenf01/skinCare",
      externalLink: "",
    },
  },
  {
    index: 3,
    image: "/images/shortly.png",
    stack: "MERN Stack Project",
    projectName: "Shortly-URL Shortener",
    projectLink: "https://zareen-shortly.vercel.app/",
    projectDescription:
      "Shortly is your go-to solution for transforming cumbersome URLs into concise, easy-to-share links. Whether you're sharing links on social media, emails, or documents, Shortly streamlines the process with its intuitive interface and powerful features. Quickly shorten any URL with Shortly's efficient service.",
    projectTech: [
      "React",
      "TypeScript",
      "Tailwind",
      "MongoDB",
      "Express",
      "Nodejs",
    ],
    projectExternalLinks: {
      github: "https://github.com/zareenf01/Shortly",
      externalLink: "",
    },
  },
  {
    index: 4,
    image: "/images/mood-track.png",
    projectName: "Mood tracker",
    projectLink: "https://zareen-mood-tracker.vercel.app/",
    projectDescription:
      "MindSpace is a simple yet powerful mood tracker built with Next.js. Track your daily moods using an interactive calendar, reflect on your emotional patterns, and unwind with guided breathing exercises.",
    projectTech: ["Nextjs", "TypeScript", "Tailwind", "Framer"],
    projectExternalLinks: {
      github: "https://github.com/zareenf01/mood-tracker",
      externalLink: "",
    },
  },

  {
    index: 5,
    image: "/images/spotify.png",
    projectName: "Spotify Clone",
    projectLink: "",
    projectDescription:
      "Spotify Clone is a web application built using React and the Spotify Web API. It mimics the functionality of the Spotify web player, allowing users to authenticate with their Spotify accounts and access various features like viewing playlists, recently played, search tracks, and exploring recommendations.",
    projectTech: ["React", "Redux", "Tailwind", "Spotify-web-API"],
    projectExternalLinks: {
      github: "https://github.com/zareenf01/spotify-clone",
      externalLink: "",
    },
  },
];

export const MernStack = [
  {
    index: 1,
    image: "/images/shortly.png",
    stack: "MERN Stack Project",
    projectName: "Shortly-URL Shorter",
    projectLink: "https://zareen-shortly.vercel.app/",
    projectDescription:
      "Shortly is your go-to solution for transforming cumbersome URLs into concise, easy-to-share links. Whether you're sharing links on social media, emails, or documents, Shortly streamlines the process with its intuitive interface and powerful features. Quickly shorten any URL with Shortly's efficient service.",
    projectTech: [
      "React",
      "TypeScript",
      "Tailwind",
      "MongoDB",
      "Express",
      "Nodejs",
    ],
    projectExternalLinks: {
      github: "https://github.com/zareenf01/Shortly",
      externalLink: "",
    },
  },
];
