import type { Metadata } from "next";
import { Inter } from "next/font/google";
import { Analytics } from "@vercel/analytics/next";
import "./globals.css";
import { SparklesCore } from "./components/ui/Sparkle";
import { GridBackgroundDemo } from "./components/ui/GridBg";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Zareen-Portfolio",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className="dark h-screen px-5 md:px-20 bg-black">
      <body
        className={`${inter.className} dark:bg-background min-h-screen relative bg-black`}
      >
        <div className="fixed inset-0 z-0">
          <GridBackgroundDemo />
        </div>
        <div className="px-5 md:px-10 relative">
          <div className="relative ">
            <div className="relative z-10">
              {children}
              <Analytics />
            </div>
          </div>
        </div>
      </body>
    </html>
  );
}
