import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { SparklesCore } from "./components/ui/Sparkle";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Zareen-Portfolio",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className="bg-black h-screen px-5 md:px-20">
      <body className={inter.className}>
        <SparklesCore
          className="absolute inset-0 z-0 pointer-events-none"
          background="#000" 
          particleDensity={4}
          speed={4}
          minSize={1}
          maxSize={3}
          particleColor="#ffffff"
        />
        <div className="relative z-10">{children}</div>
      </body>
    </html>
  );
}
